name: log_analyzer CI/CD # pipeline's name that will appear in Github Actions

on: # events that trigger our pipeline: push on any branch and release creation
  push

jobs: # jobs. We will have two jobs (test and publish) with multiple steps.
  test:
    # Our test job will run on ubuntu.
    # We define matrix strategy for python-version so that 
    # our tests are run on multiple python versions:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: [3.9.3.10]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image # install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.0.10
      - name: Install dependencies # install all dependencies
        run: poetry install
      - name: Pylint # Run pylint static analysis
        run: |
          poetry run pylint
      - name: mypy  # Run mypy static analysis
        run: |
          poetry run mypy
      - name: Pytest # Run pytest
        run: |
          poetry run pytest tests
